# Generated by Django 4.0.5 on 2022-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='lastFed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='lastPooped',
            field=models.DateTimeField(),
        ),
    ]
