# Generated by Django 4.0.5 on 2022-06-19 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melly', '0002_alter_dogs_lastfed_alter_dogs_lastpooped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='age',
        ),
        migrations.AddField(
            model_name='dogs',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 10, 46, 23, 963727)),
        ),
    ]
