# Generated by Django 4.0.5 on 2022-06-19 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('melly', '0003_remove_dogs_age_dogs_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
